import type { INodeProperties } from 'n8n-workflow';

export const bingSearchOptions: INodeProperties[] = [
	{
		displayName: 'Max Pages',
		name: 'max_pages',
		type: 'number',
		default: 1,
		description: 'Maximum number of Bing search result pages to fetch. Each page costs 10 credits.',
		typeOptions: { minValue: 1 },
	},
	{
		displayName: 'Result Count',
		name: 'count',
		type: 'number',
		default: undefined,
		description: 'Number of search results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
	},
	{
		displayName: 'Language',
		name: 'setLang',
		type: 'string',
		default: '',
		description: 'Language code for search results, for example en, es, fr, or de',
	},
	{
		displayName: 'Country Code',
		name: 'cc',
		type: 'string',
		default: '',
		description: 'Country code for localized search results, for example US, GB, or DE',
	},
	{
		displayName: 'Geolocation',
		name: 'geolocation',
		type: 'string',
		default: '',
		description: 'Geographic location for localized results. Use random for randomized geolocation.',
	},
	{
		displayName: 'Device',
		name: 'device',
		type: 'options',
		default: 'desktop',
		options: [
			{ name: 'Desktop', value: 'desktop' },
			{ name: 'Mobile', value: 'mobile' },
			{ name: 'Tablet', value: 'tablet' },
		],
		description: 'Device type to simulate during search',
	},
	{
		displayName: 'Auto Crawling',
		name: 'auto_crawling',
		type: 'boolean',
		default: false,
		description: 'Whether to automatically crawl each search result URL and include page content',
	},
	{
		displayName: 'Copilot Answer',
		name: 'copilot_answer',
		type: 'boolean',
		default: true,
		description: 'Whether to include Copilot AI-generated answer cards in the SERP results',
	},
	{
		displayName: 'Questions and Answers',
		name: 'questions_answers',
		type: 'boolean',
		default: true,
		description: 'Whether to include People Also Ask question-and-answer cards in the results',
	},
	{
		displayName: 'Related Queries',
		name: 'related_queries',
		type: 'boolean',
		default: true,
		description: 'Whether to include related search query suggestions',
	},
	{
		displayName: 'Sidebar',
		name: 'sidebar',
		type: 'boolean',
		default: true,
		description: 'Whether to include sidebar data such as knowledge panels and local results',
	},
	{
		displayName: 'Direct Answer',
		name: 'direct_answer',
		type: 'boolean',
		default: true,
		description: 'Whether to include direct answer boxes and instant answers',
	},
	{
		displayName: 'Raw HTML',
		name: 'raw_html',
		type: 'boolean',
		default: false,
		description: 'Whether to return the original HTML source of each result page',
	},
	{
		displayName: 'Enhanced HTML',
		name: 'enhanced_html',
		type: 'boolean',
		default: false,
		description: 'Whether to return cleaned HTML with ads, scripts, and tracking removed',
	},
	{
		displayName: 'Page Text',
		name: 'page_text',
		type: 'boolean',
		default: false,
		description: 'Whether to return plain text content extracted from each result page',
	},
	{
		displayName: 'Markdown',
		name: 'markdown',
		type: 'boolean',
		default: false,
		description: 'Whether to return crawled page content as structured Markdown, recommended for RAG and LLM workflows',
	},
];

export const googleSearchOptions: INodeProperties[] = [
	{
		displayName: 'Country',
		name: 'gl',
		type: 'string',
		default: 'us',
		description: 'Country for search results as an ISO 3166-1 alpha-2 code, for example us, gb, eg, de, or fr',
	},
	{
		displayName: 'Language',
		name: 'hl',
		type: 'string',
		default: 'en',
		description: 'Language for results as an IETF language tag, for example en, ar, fr, or de',
	},
	{
		displayName: 'Freshness Filter',
		name: 'tbs',
		type: 'options',
		default: '',
		description: 'Optional time-based filter for result freshness',
		options: [
			{ name: 'None', value: '' },
			{ name: 'Past Day', value: 'qdr:d' },
			{ name: 'Past Hour', value: 'qdr:h' },
			{ name: 'Past Month', value: 'qdr:m' },
			{ name: 'Past Week', value: 'qdr:w' },
			{ name: 'Past Year', value: 'qdr:y' },
		],
	},
	{
		displayName: 'Page',
		name: 'page',
		type: 'number',
		default: 1,
		description: 'Page number of Google results to fetch, 1-indexed',
		typeOptions: { minValue: 1 },
	},
	{
		displayName: 'Results Per Page',
		name: 'num',
		type: 'number',
		default: 10,
		description: 'Number of results per page',
		typeOptions: { minValue: 1, maxValue: 100 },
	},
	{
		displayName: 'Search Type',
		name: 'type',
		type: 'options',
		default: 'search',
		description: 'Google vertical to query',
		options: [
			{ name: 'Images', value: 'images' },
			{ name: 'News', value: 'news' },
			{ name: 'Places', value: 'places' },
			{ name: 'Shopping', value: 'shopping' },
			{ name: 'Standard Web Search', value: 'search' },
		],
	},
];

export const googleMapsOptions: INodeProperties[] = [
	{
		displayName: 'Language',
		name: 'hl',
		type: 'string',
		default: '',
		description: 'Language code for returned place text, for example en, ar, fr, or de',
	},
	{
		displayName: 'Location Bias',
		name: 'll',
		type: 'string',
		default: '',
		description: 'Location bias in the format @latitude,longitude,zoomz, for example @48.8566,2.3522,15z',
	},
	{
		displayName: 'Place ID',
		name: 'placeId',
		type: 'string',
		default: '',
		description: 'Google Place ID for looking up a specific place directly',
	},
	{
		displayName: 'CID',
		name: 'cid',
		type: 'string',
		default: '',
		description: 'Google numeric business/customer ID for targeting a specific business listing',
	},
];

export const crawlerOptions: INodeProperties[] = [
	{
		displayName: 'Render JavaScript',
		name: 'render_js',
		type: 'boolean',
		default: false,
		description: 'Whether to use browser rendering for JavaScript-heavy sites. Costs 10 credits per URL instead of 1.',
	},
	{
		displayName: 'Geolocation',
		name: 'geolocation',
		type: 'string',
		default: '',
		description: 'ISO 3166-1 alpha-2 country code for crawl geolocation, for example us, gb, or de',
	},
	{
		displayName: 'Raw HTML',
		name: 'raw_html',
		type: 'boolean',
		default: false,
		description: 'Whether to return the raw HTML as-is from the page source',
	},
	{
		displayName: 'Enhanced HTML',
		name: 'enhanced_html',
		type: 'boolean',
		default: true,
		description: 'Whether to return cleaned/sanitized HTML with ads, scripts, and tracking removed',
	},
	{
		displayName: 'Page Text',
		name: 'page_text',
		type: 'boolean',
		default: false,
		description: 'Whether to return plain-text extraction of the page content',
	},
	{
		displayName: 'Markdown',
		name: 'markdown',
		type: 'boolean',
		default: true,
		description: 'Whether to return markdown conversion, recommended for RAG and LLM applications',
	},
	{
		displayName: 'Screenshot',
		name: 'screenshot',
		type: 'boolean',
		default: false,
		description: 'Whether to capture a screenshot of the page. Only available when Render JavaScript is enabled.',
	},
	{
		displayName: 'Full Page Screenshot',
		name: 'screenshot_full_page',
		type: 'boolean',
		default: false,
		description: 'Whether to capture a full-page screenshot instead of only the viewport. Only available when Screenshot is enabled.',
		displayOptions: {
			show: {
				screenshot: [true],
			},
		},
	},
];

export const headfulBrowserOptions: INodeProperties[] = [
	{
		displayName: 'Country',
		name: 'country',
		type: 'string',
		default: 'us',
		description: 'ISO 3166-1 alpha-2 country code for residential proxy geolocation, for example us, gb, de, fr, jp, in, br, ca, or au',
	},
	{
		displayName: 'Output Format',
		name: 'output_format',
		type: 'options',
		default: 'markdown',
		description: 'Output format for the crawled page content',
		options: [
			{ name: 'Markdown', value: 'markdown' },
			{ name: 'Enhanced HTML', value: 'enhanced_html' },
			{ name: 'Raw HTML', value: 'raw_html' },
			{ name: 'Page Text', value: 'page_text' },
		],
	},
	{
		displayName: 'Screenshot',
		name: 'screenshot',
		type: 'boolean',
		default: false,
		description: 'Whether to capture a full-page screenshot of the rendered page. The response returns a screenshot URL.',
	},
];

export const searchOptions = bingSearchOptions;
